// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using libescaner.Core;

namespace libescaner.Migrations
{
    [DbContext(typeof(LibEscanerDbContext))]
    [Migration("20200225230115_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("libescaner.Model.Breakers.Credito", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdAcreditado")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IdCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NumeroCredito")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.HasKey("Id");

                    b.HasIndex("IdAcreditado");

                    b.HasIndex("IdCliente");

                    b.ToTable("BRE_CREDITO");
                });

            modelBuilder.Entity("libescaner.Model.Catalog.TipoArchivo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClaveTipoArchivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreTipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("C_TIPOARCHIVO");
                });

            modelBuilder.Entity("libescaner.Model.Entities.Acreditado", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("NumeroLoan")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.HasKey("Id");

                    b.ToTable("T_ACREDITADO");
                });

            modelBuilder.Entity("libescaner.Model.Entities.Archivo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdAcreditado")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IdTipoArchivo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("PathArchivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Titulo")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.HasKey("Id");

                    b.HasIndex("IdAcreditado");

                    b.HasIndex("IdTipoArchivo");

                    b.ToTable("T_ARCHIVO");
                });

            modelBuilder.Entity("libescaner.Model.Entities.Cliente", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("T_CLIENTE");
                });

            modelBuilder.Entity("libescaner.Model.Breakers.Credito", b =>
                {
                    b.HasOne("libescaner.Model.Entities.Acreditado", "Acreditado")
                        .WithMany("Creditos")
                        .HasForeignKey("IdAcreditado")
                        .IsRequired();

                    b.HasOne("libescaner.Model.Entities.Cliente", "Cliente")
                        .WithMany("Creditos")
                        .HasForeignKey("IdCliente")
                        .IsRequired();
                });

            modelBuilder.Entity("libescaner.Model.Entities.Archivo", b =>
                {
                    b.HasOne("libescaner.Model.Entities.Acreditado", "Acreditado")
                        .WithMany("Archivos")
                        .HasForeignKey("IdAcreditado")
                        .IsRequired();

                    b.HasOne("libescaner.Model.Catalog.TipoArchivo", "TipoArchivo")
                        .WithMany("Archivos")
                        .HasForeignKey("IdTipoArchivo");
                });
#pragma warning restore 612, 618
        }
    }
}
